// User types
export const SET_USER = 'SET_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const LOADING_USER = 'LOADING_USER';
export const LOADING_USERS = 'LOADING_USERS';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
export const SET_USERS = 'SET_USERS';

// UI types
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// Post types
export const SET_POSTS = 'SET_POSTS';
export const SET_POST = 'SET_POST';
export const FAV_POST = 'FAV_POST';
export const UNFAV_POST = 'UNFAV_POST';
export const DELETE_POST = 'DELETE_POST';
export const POST_POST = 'POST_POST';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const TOGGLE_POST_UPVOTE = 'TOGGLE_POST_UPVOTE';
export const TOGGLE_POST_DOWNVOTE = 'TOGGLE_POST_DOWNVOTE';
export const TOGGLE_COMMENT_UPVOTE = 'TOGGLE_COMMENT_UPVOTE';
export const TOGGLE_COMMENT_DOWNVOTE = 'TOGGLE_COMMENT_DOWNVOTE';
export const ADD_COMMENT = 'ADD_COMMENT';
