export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const TOGGLE_COMMENT_UPVOTE = 'TOGGLE_COMMENT_UPVOTE';
export const TOGGLE_COMMENT_DOWNVOTE = 'TOGGLE_COMMENT_DOWNVOTE';
export const LOADING_COMMENT = 'LOADING_COMMENT';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
